version: "3.1"

services:
  roundebounce:
    image: roundcube/roundcubemail:latest
    container_name: roundebounce
    ports:
      - 8000:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.gmail.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993

  nginx:
    image: trafex/alpine-nginx-php7:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html
